# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "pastes", :force => true do |t|
    t.column "code",        :string,   :limit => 5,                     :null => false
    t.column "paste",       :text,                                      :null => false
    t.column "created_at",  :datetime,                                  :null => false
    t.column "modified_at", :datetime
    t.column "private",     :boolean,                :default => false, :null => false
    t.column "ip",          :string,   :limit => 15
  end

end
